# Generated by Django 6.0.3 on 2026-03-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_name_initials', models.CharField(blank=True, max_length=10, null=True, verbose_name='Company Name Initials')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='site_settings/logo/light/', verbose_name='Light Logo')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='site_settings/logo/dark/', verbose_name='Dark Logo')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('contact_address', models.TextField(blank=True, null=True, verbose_name='Contact Address')),
                ('contact_address_map_url', models.URLField(blank=True, null=True, verbose_name='Contact Address Map URL')),
                ('whatsapp_url', models.URLField(blank=True, null=True, verbose_name='WhatsApp URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('x_url', models.URLField(blank=True, null=True, verbose_name='X URL')),
            ],
            options={
                'verbose_name': 'Global Site Settings',
            },
        ),
    ]
